-- Generated by nwg-displays on 2026-06-14 at 03:42:54. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@59.94",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    disabled = true
})
